In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
loan_df = pd.read_csv("D://Loan_Default.csv")

In [3]:
loan_df["income"] = loan_df["income"].fillna(loan_df["income"].mean())
loan_df["loan_amount"] = loan_df["loan_amount"].fillna(loan_df["loan_amount"].mean())
loan_df["rate_of_interest"] = loan_df["rate_of_interest"].fillna(loan_df["rate_of_interest"].mean())
loan_df["approv_in_adv"] = loan_df["approv_in_adv"].fillna(loan_df["approv_in_adv"].mode())



loan_df = loan_df.assign(
    total_units = loan_df["total_units"].map({
        "1U": "1U",
        "2U": "2U+",
        "3U": "2U+",
        "4U": "2U+"}),
    loan_amt_v_income = loan_df["loan_amount"]/loan_df["income"]
)

loan_df.head()

ID  year loan_limit             Gender approv_in_adv loan_type  \
0  24890  2019         cf  Sex Not Available         nopre     type1   
1  24891  2019         cf               Male         nopre     type2   
2  24892  2019         cf               Male           pre     type1   
3  24893  2019         cf               Male         nopre     type1   
4  24894  2019         cf              Joint           pre     type1   

  loan_purpose Credit_Worthiness open_credit business_or_commercial  ...  \
0           p1                l1        nopc                  nob/c  ...   
1           p1                l1        nopc                    b/c  ...   
2           p1                l1        nopc                  nob/c  ...   
3           p4                l1        nopc                  nob/c  ...   
4           p1                l1        nopc                  nob/c  ...   

   Credit_Score  co-applicant_credit_type    age  submission_of_application  \
0           758                       CIB  25-34                    to_inst   
1           552                       EXP  55-64                    to_inst   
2           834                       CIB  35-44                    to_inst   
3           587                       CIB  45-54                   not_inst   
4           602                       EXP  25-34                   not_inst   

         LTV Region Security_Type Status  dtir1 loan_amt_v_income  
0  98.728814  south        direct      1   45.0         66.954023  
1        NaN  North        direct      1    NaN         41.465863  
2  80.019685  south        direct      0   46.0         42.879747  
3  69.376900  North        direct      0   42.0         38.425926  
4  91.886544  North        direct      0   39.0         66.714559  

[5 rows x 35 columns]

In [4]:
prep_loan_df = loan_df.drop([
    "year", 
     "ID", 
     "open_credit", 
    "construction_type", 
    "Security_Type", 
    "Secured_by"], 
    axis=1
)

prep_loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 29 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   loan_limit                 145326 non-null  object 
 1   Gender                     148670 non-null  object 
 2   approv_in_adv              147762 non-null  object 
 3   loan_type                  148670 non-null  object 
 4   loan_purpose               148536 non-null  object 
 5   Credit_Worthiness          148670 non-null  object 
 6   business_or_commercial     148670 non-null  object 
 7   loan_amount                148670 non-null  int64  
 8   rate_of_interest           148670 non-null  float64
 9   Interest_rate_spread       112031 non-null  float64
 10  Upfront_charges            109028 non-null  float64
 11  term                       148629 non-null  float64
 12  Neg_ammortization          148549 non-null  object 
 13  interest_only              14

In [5]:
from sklearn.model_selection import train_test_split

features = [
    "loan_amount", 
    "income", 
    "Gender",
    "rate_of_interest",
    "age",
    "lump_sum_payment",
    "credit_type",
    "total_units",
    "Credit_Worthiness",
    "Credit_Score",
    "approv_in_adv", 

]

X = pd.get_dummies(prep_loan_df[features], drop_first=True)
y = prep_loan_df["Status"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=12345)


In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
lr = LogisticRegression()
lr = lr.fit(X_train, y_train)

In [8]:
lr.coef_
# as our loan amount increases then the probability of default decreases

array([[ 4.65760300e-07, -2.80958810e-05, -6.11919102e-01,
         3.04151895e-03, -4.44092258e-01,  9.83009987e-02,
         2.75542628e-01, -1.63048493e-01, -3.38193178e-03,
         4.14871584e-02,  3.06066124e-02,  6.31205221e-03,
         5.28064864e-02, -5.52657699e-01, -9.17388212e-01,
         2.64602443e+00, -8.61075266e-01,  5.50537270e-02,
         1.03130919e-01, -2.34506847e-01]])

In [9]:
lr.intercept_
# more defaults then non-defaults
# positive class is the defualters which are rare

array([-0.14335444])

In [10]:
lr.score(X_train, y_train)
# accuracy

0.8529797538171789

In [11]:
lr.score(X_test, y_test)

0.8525929911885384

In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
confusion_matrix(y_test, lr.predict(X_test))

array([[22214,   131],
       [ 4252,  3137]], dtype=int64)

In [14]:
# How many +ves were predicted
#Hyper parameter tuning
#feature engineering
#feature selection 
#unbalanced classes
# How much data transformation will contribute in terms of increasing it for more appropriate analysis.